<?php

namespace MMichel\ExamBundle\Form\Type;


use MMichel\ExamBundle\Form\EventListener\QuestionTypeResizeFormListener;
use MMichel\ExamBundle\Form\Factory\PolymorphCollectionFormFactory;
use MMichel\ExamBundle\Form\QuestionFormFactory;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\EventListener\ResizeFormListener;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PolymorphCollectionType extends CollectionType
{

    protected $formFactory;

    public function __construct(PolymorphCollectionFormFactory $factory) {
        $this->formFactory = $factory;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
//        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        if ($options['allow_add'] && $options['prototype']) {
            $prototype = $builder->create($options['prototype_name'], $options['type'], array_replace(array(
                'label' => $options['prototype_name'].'label__',
            ), $options['options']));
            $builder->setAttribute('prototype', $prototype->getForm());
        }

        $resizeListener = new QuestionTypeResizeFormListener(
            $options['type'],
            $options['options'],
            $options['allow_add'],
            $options['allow_delete'],
            $options['delete_empty'],
            $this->formFactory
        );

        $builder->addEventSubscriber($resizeListener);
    }


//    public function configureOptions(OptionsResolver $resolver)
//    {
//        parent::configureOptions($resolver);
//        $resolver->setDefaults(array(
//            'type_callback' => null,
//        ));
//        $resolver->setAllowedTypes('type_factory', array('null', 'callable', 'MMichel\ExamBundle\Form\Factory\QuestionFormFactory'));
//    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return 'polymorph_collection';
    }
}