<?php

namespace MMichel\ExamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExamQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamQuestionRepository extends EntityRepository
{
}
